project_id = "hikhnmuckfopyzxkdeus"

[functions.create-agent]
verify_jwt = true

[functions.send-setup-link]
verify_jwt = true

[functions.agent-chat]
verify_jwt = true

[functions.agent-chat-rag]
verify_jwt = true

[functions.send-contracting-packet]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.send-agent-inquiry]
verify_jwt = false

[functions.generate-contracting-pdf]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.extract-pdf-fields]
verify_jwt = false

[functions.pdf-field-audit]
verify_jwt = false
