project_id = "hikhnmuckfopyzxkdeus"

[functions.create-agent]
verify_jwt = true

[functions.send-setup-link]
verify_jwt = true

[functions.agent-chat]
verify_jwt = true

[functions.agent-chat-rag]
verify_jwt = true

[functions.send-contracting-packet]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.send-agent-inquiry]
verify_jwt = false
