project_id = "clcidrccnmetckkawtkq"

[functions.send-contracting-packet]
verify_jwt = false

[functions.validate-password]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.agent-chat-rag]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.process-documents-background]
verify_jwt = false